version: '3.8'

services:
  postgres-dw:
    image: postgres:13
    container_name: postgres_dw
    environment:
      - POSTGRES_USER=warehouse_user
      - POSTGRES_PASSWORD=warehouse_password
      - POSTGRES_DB=data_warehouse
    ports:
      - "5434:5432" # Mapped to 5434 to avoid conflict with MySQL (3307) and Airflow Postgres (5432)
    volumes:
      - postgres_dw_data:/var/lib/postgresql/data
      - ./src/datawarehouse/star_schema_dwh.sql:/docker-entrypoint-initdb.d/star_schema_dwh.sql
    networks:
      - my_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U warehouse_user -d data_warehouse" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dw_data:


networks:
  my_network:
    external: true
